---
models:
  - name: LibreFOMOs-point
    image_size: 96
    batch_size: -1
  - name: LibreFOMOm-point
    image_size: 192
    batch_size: -1
  - name: LibreFOMOl-point
    image_size: 224
    batch_size: -1
  - name: LibreYOLO9c
    image_size: 640
    batch_size: -1
  - name: LibreYOLO9m
    image_size: 640
    batch_size: -1
  - name: LibreYOLO9s
    image_size: 640
    batch_size: -1
  - name: LibreYOLO9t
    image_size: 640
    batch_size: -1
  - name: LibreYOLO9E2Ec
    image_size: 640
    batch_size: -1
  - name: LibreYOLOE2E9m
    image_size: 640
    batch_size: -1
  - name: LibreYOLE2E9s
    image_size: 640
    batch_size: -1
  - name: LibreYOLO9E2Et
    image_size: 640
    batch_size: -1
dataset:
  name: andreasmoegelmose/multiview-traffic-intersection-dataset
  directory: dataset
epochs: 10  # Times (epochs) to train the model on the dataset.
sleep_minutes: 0  # Minutes between training sessions. Set to 0 to disable waiting.
learn_rate: 0.0003  # 3e-4
